### ISSUE TITLE
Build number wraps on overview even at wide screen widths

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#461] opened 2016-08-23 18:28 UTC
![screen_shot_2016-08-23_at_2_27_18_pm](https://cloud.githubusercontent.com/assets/1167259/17904554/c88d07be-693d-11e6-827f-5fff3ca313b9.png)

/cc @jwforres @rhamilto

**Comment by rhamilto** [comment] 2016-08-23 18:54
@spadgett, I'm not able to reproduce this.  Tips on setup?

**Comment by spadgett** [comment] 2016-08-23 19:21
@rhamilto Hm, I'm only seeing this in the built openshift binary, not in the my development environment

**Comment by rhamilto** [comment] 2016-08-24 13:16
This appears to be a whitespace issue related to template minification?

**Comment by rhamilto** [comment] 2016-08-24 13:23
Removing the whitespace in https://github.com/openshift/origin-web-console/blob/master/app/views/_triggers.html#L14-L16 appears to fix it.

**Comment by jwforres** [comment] 2016-08-24 13:24
Fixed in #468

**Closed** 2016-08-24 13:24 UTC
Labels: area/styles, kind/bug, priority/P3
