### ISSUE TITLE
Improve build pipeline display when pipeline stages wrap

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#113] opened 2016-06-24 21:08 UTC
@jwforres @spadgett

**Comment by sg00dwin** [comment] 2016-06-24 21:08
<img width="1058" alt="screen shot 2016-06-24 at 4 06 06 pm" src="https://cloud.githubusercontent.com/assets/1874151/16350685/44593988-3a2e-11e6-94a2-51ff7413ac40.png">

<img width="1038" alt="screen shot 2016-06-24 at 4 44 47 pm" src="https://cloud.githubusercontent.com/assets/1874151/16350689/49299f52-3a2e-11e6-94b7-b2ddf4f29553.png">

<img width="1028" alt="screen shot 2016-06-24 at 4 54 45 pm" src="https://cloud.githubusercontent.com/assets/1874151/16350694/4d22212e-3a2e-11e6-8911-5c178eacef9f.png">

<img width="1027" alt="screen shot 2016-06-24 at 5 02 15 pm" src="https://cloud.githubusercontent.com/assets/1874151/16350698/52c52248-3a2e-11e6-9096-b645881fb9a8.png">

**Comment by jwforres** [comment] 2016-06-27 13:18
@ajacobs21e @sjcox-rh @rhamilto thoughts on these?  They are options until we can implement scrolling.

**Comment by rhamilto** [comment] 2016-06-27 13:56
I prefer "Thicker row border", although I think I would reduce the outermost left and right borders back to 1px, as it creates nice, clean separation without unnecessary "noise".

**Comment by sg00dwin** [comment] 2016-06-29 19:22
Additional options...

<img width="1044" alt="screen shot 2016-06-29 at 3 15 19 pm" src="https://cloud.githubusercontent.com/assets/1874151/16465456/d0c13c72-3e0c-11e6-81e4-ce4278fcad9e.png">
<img width="1051" alt="screen shot 2016-06-29 at 2 49 01 pm" src="https://cloud.githubusercontent.com/assets/1874151/16465457/d0c20e04-3e0c-11e6-8aeb-d8d0d077d361.png">
![new](https://cloud.githubusercontent.com/assets/1874151/16465540/4d1a2f18-3e0d-11e6-9b46-fb5317fcb84f.png)

**Comment by rhamilto** [comment] 2016-06-29 19:52
Nice work, @sg00dwin!  My opinion remains unchanged, however.  I think "Thicker row border" provides the needed separation without additional noise.

**Comment by ajacobs21e** [comment] 2016-07-05 05:26
@sg00dwin is horizontal scroll an option?

**Comment by spadgett** [comment] 2016-07-05 13:17
@ajacobs21e It's an option. The problem is all the interesting stuff is happening off-screen: the currently running stage, a paused stage needing approval, future stages (when we have them), etc.

**Comment by ajacobs21e** [comment] 2016-07-05 21:19
Here are some ideas for how to display a pipeline with horizontal scroll: 
![buildpage](https://cloud.githubusercontent.com/assets/6415742/16600169/dab9a1da-42d3-11e6-9ae8-ab589e702ca1.png)

In the original mockups, the wider steps have more visual weight which implies more importance. Since that isn't the case the steps should all be the same width. It's also difficult to understand that the pipeline wraps. If it has to wrap, there needs to be a better visual indication of what the wrapping means. The wrapping will also be difficult to maintain if we introduce fan out / in pipelines.

**Comment by ajacobs21e** [comment] 2016-07-05 21:20
Also addresses https://github.com/openshift/origin-web-console/issues/126

**Comment by jwforres** [comment] 2016-07-05 21:26
cc @rhamilto

**Comment by spadgett** [comment] 2016-07-06 21:09
How far does it scroll when you click the arrow? If I scroll over to look at something and a new stage starts, will it scroll me back? How will this translate to mobile?

I don't think we should collapse down complete stages or steps for running pipelines. That hasn't been popular on the overview.

It feels weird to have scrolling arrows instead of just a scrollbar.

**Comment by spadgett** [comment] 2016-07-06 21:15
It also seems odd to have the duration in a different place for complete vs running stages that otherwise look the same. I'd rather have the indeterminate progress bar behind the blue running icon, with the duration below like other stages.

**Comment by ajacobs21e** [comment] 2016-07-11 21:25
@spadgett 
It would scroll one step at a time. If it makes sense to have a second "go to end" sort of button we could do that too. 
I had a design for a mobile pipeline that was tested at Summit but I haven't looked at those results yet.

Do you prefer having items off the screen instead of collapsing?

I asked SJ to join so she can comment on the arrow design.

**Comment by ajacobs21e** [comment] 2016-07-12 04:46
@sjcox-rh ^

**Comment by sjcox-rh** [comment] 2016-07-12 05:09
@ajacobs21e is right about the scrolling @spadgett.  It would be one step at a time.  Perhaps a way to "go to the end" is to click and hold the arrow?  Also, it might be a good idea to have a "go to active" button of some sort so if you scroll away from the active stage you could easily get back. To respond to your questions @spadgett, if we have the active button, perhaps that could glow if you have scrolled away and a new stage has started.

**Comment by rhamilto** [comment] 2016-07-13 20:33
I believe we have agreement that individual stages should have a set width (that is, not flex).  Anyone disagree?

But we've yet to come to consensus on arrows vs. not?

**Comment by spadgett** [comment] 2016-07-14 12:47
Whatever solution we come up with needs to work on mobile.

Fixed width is probably better, although we should make sure a pipeline with two stages looks good. That might common, and our sample pipeline template only has two.

**Comment by ajacobs21e** [comment] 2016-07-14 15:32
@rhamilto @spadgett I'm at a conference today and can't reply until later tonight or tomorrow. I will get back to this then.

**Comment by rhamilto** [comment] 2016-07-14 20:41
@ajacobs21e, let's plan to discuss tomorrow.  I think we'll need to come up with an interim solution as we don't yet have environments and are likely to not have future stages.  :/

**Comment by rhamilto** [comment] 2016-07-15 19:49
Given the technical challenges of implementing the [aforementioned design](https://github.com/openshift/origin-web-console/issues/113#issuecomment-230606479), I've come up with an alternate design idea based on conversations with @ajacobs21e.  

Requirements:

* individual stages always have the same width regardless of which build they are a part of or how many stages are included in each build, but remain "flex"ible
* the existing stage wrapping behavior is maintained in order to avoid the technical overhead of trying to figure out how to implement the horizontal scroll solution
* the stages indicate a flow from left to right, even if they wrap
* the design can accommodate environments and future stages once they are available for us to add

So what about something like this?  Note:  the mockups are a little crude in that we'll likely not have as many stages as depicted until environments and future stages are added, but I wanted it to be clear how the design accommodates multiple lines of stages.

![screen shot 2016-07-15 at 2 27 19 pm](https://cloud.githubusercontent.com/assets/895728/16886503/c7ae4e02-4aa2-11e6-8019-0bad83cc94e3.PNG)
![screen shot 2016-07-15 at 2 26 55 pm](https://cloud.githubusercontent.com/assets/895728/16886505/c7af6ba2-4aa2-11e6-8873-eddc55cc2de1.PNG)
![screen shot 2016-07-15 at 2 26 28 pm](https://cloud.githubusercontent.com/assets/895728/16886504/c7af2bb0-4aa2-11e6-9d97-72aec7a3b312.PNG)
![screen shot 2016-07-15 at 2 26 11 pm](https://cloud.githubusercontent.com/assets/895728/16886502/c7ae2094-4aa2-11e6-8b46-0f656de9e289.PNG)

A rough idea of how this same design could accommodate environment headers:

![with-environments](https://cloud.githubusercontent.com/assets/895728/16886526/e5f657b0-4aa2-11e6-9b25-34e6b80b310f.png)

What do you think?

**Comment by ajacobs21e** [comment] 2016-07-16 05:08
@rhamilto it's coming along great! One small change - I made the inside row divider bars not touch the edges:
![1](https://cloud.githubusercontent.com/assets/6415742/16892898/bdbe33f4-4af1-11e6-9505-ae923fad05db.png)

I made this really quickly don't laugh... could we do something like this?
![2](https://cloud.githubusercontent.com/assets/6415742/16892901/daafa416-4af1-11e6-8059-b06e62fdfbb6.png)

**Comment by rhamilto** [comment] 2016-07-18 12:17
@ajacobs21e, to me the divider bars not touching the edges gets weird when you consider the forthcoming stages design header idea since we're using the header to show the continuation of the stage from one row to the next.  Thoughts?

**Comment by rhamilto** [comment] 2016-07-18 17:22
@sg00dwin, @jwforres, @spadgett, you guys mind taking a look?

<img width="930" alt="screen shot 2016-07-18 at 1 18 35 pm" src="https://cloud.githubusercontent.com/assets/895728/16923883/89760914-4cea-11e6-9dbf-242e79f671e6.PNG">
<img width="1413" alt="screen shot 2016-07-18 at 1 19 08 pm" src="https://cloud.githubusercontent.com/assets/895728/16923884/89769410-4cea-11e6-983f-4de9562d3114.PNG">
<img width="778" alt="screen shot 2016-07-18 at 1 19 24 pm" src="https://cloud.githubusercontent.com/assets/895728/16923886/897a6702-4cea-11e6-8c7f-93314a79a4b8.PNG">
<img width="414" alt="screen shot 2016-07-18 at 1 19 43 pm" src="https://cloud.githubusercontent.com/assets/895728/16923885/8979ebe2-4cea-11e6-9706-4f9ae20d889a.PNG">

**Comment by jwforres** [comment] 2016-07-18 19:45
I would be worried about the width of the stage at the tablet? resolution, the stages names come from the user and realistically could be longer then "build" or "deploy"

**Comment by spadgett** [comment] 2016-07-18 20:03
+1 on the long stage names. I don't think they'll be uncommon. See #74.

**Comment by ajacobs21e** [comment] 2016-07-19 04:30
@rhamilto having the stage name header touch the edges didn't look so bad when it was just one pipeline. I think there needs to be a stronger visual indicator of what's a continued pipeline vs the next pipeline. Scanning down the pipelines you may not see the leftmost column with the build name etc or the slightly thicker lines between builds.

**Comment by rhamilto** [comment] 2016-07-19 14:03
> @rhamilto having the stage name header touch the edges didn't look so bad when it was just one pipeline. I think there needs to be a stronger visual indicator of what's a continued pipeline vs the next pipeline. Scanning down the pipelines you may not see the leftmost column with the build name etc or the slightly thicker lines between builds.

@ajacobs21e, In an effort to keep the current work that doesn't involve environments or future stages in scope, are you comfortable with us revisiting that when the time comes?  I think we can find a solution that works within the current context (i.e., I don't think we're painting ourselves in to a corner).

**Comment by rhamilto** [comment] 2016-07-19 14:06
> +1 on the long stage names. I don't think they'll be uncommon. See #74.

I've revised the sizing of individual stages at various resolutions.  Better?

320px
![320 px](https://cloud.githubusercontent.com/assets/895728/16952683/3dbe8cb8-4d98-11e6-85e5-0360830edacf.PNG)

400px
![400px](https://cloud.githubusercontent.com/assets/895728/16952689/40d961c0-4d98-11e6-8ccd-d50c8462e250.png)

600px
![600px](https://cloud.githubusercontent.com/assets/895728/16952691/43baeecc-4d98-11e6-8433-804239011f1d.png)

800px
![800px](https://cloud.githubusercontent.com/assets/895728/16952697/47fa9514-4d98-11e6-89a6-ea91796b7a4f.png)

1000px
![1000px](https://cloud.githubusercontent.com/assets/895728/16952702/4bf0366a-4d98-11e6-9410-7e01941261ce.png)

1200px
![1200px](https://cloud.githubusercontent.com/assets/895728/16952703/4f0969fc-4d98-11e6-8448-1096e93b9b0c.png)

1600px
![1600px](https://cloud.githubusercontent.com/assets/895728/16952708/51e10900-4d98-11e6-8023-4d261a51d8db.png)

**Comment by jwforres** [comment] 2016-07-19 14:14
at 320px having one per row makes the arrow looks like it actually does
some action..  what if at 320px the arrow is underneath the stage and
points down?

**Comment by rhamilto** [comment] 2016-07-19 15:55
Using fa-long-arrow-right and incorporating @ajacobs21e's suggestion to preventing the bottom border from going to the edges.  If we keep the border change, we'll need to find an alternate way to demarcate environments (but I think there are viable solutions).

The downside to fa-long-arrow-right is that it takes up considerably more horizontal space, thus shrinking the stages down and causing more truncation on longer stage name labels.

320px
![320px](https://cloud.githubusercontent.com/assets/895728/16956628/3720ccae-4da7-11e6-8840-e18abfd3dc93.png)

400px
![400px](https://cloud.githubusercontent.com/assets/895728/16956633/372b7118-4da7-11e6-92ac-c684d17fa29f.png)

600px
![600px](https://cloud.githubusercontent.com/assets/895728/16956630/3728c1f2-4da7-11e6-8652-a1e65ee0ab9d.png)

800px
![800px](https://cloud.githubusercontent.com/assets/895728/16956632/3729b26a-4da7-11e6-9ba2-26e7f5cd2008.png)

1000px
![1000px](https://cloud.githubusercontent.com/assets/895728/16956629/3728981c-4da7-11e6-8290-603775141c9a.png)

1200px
![1200px](https://cloud.githubusercontent.com/assets/895728/16956631/3728e5a6-4da7-11e6-8cf4-1cdcec743242.png)

1600px
![1600px](https://cloud.githubusercontent.com/assets/895728/16956634/372bf0d4-4da7-11e6-9863-84627ba6b8a5.png)

Thoughts?

**Comment by rhamilto** [comment] 2016-07-19 16:23
Using html entity rarr instead.  Preferences?  

![screen shot 2016-07-19 at 12 16 33 pm](https://cloud.githubusercontent.com/assets/895728/16957570/d6dfdbb0-4daa-11e6-88eb-71d18b36ba48.PNG)

![screen shot 2016-07-19 at 12 21 45 pm](https://cloud.githubusercontent.com/assets/895728/16957721/949e30c0-4dab-11e6-8123-6ff95c2f8387.PNG)


If we go with fa-long-arrow-right, I think we need to update the overview deployment config so the arrows match.

**Comment by spadgett** [comment] 2016-07-19 16:28
To me, the HTML entity looks better.

**Comment by ajacobs21e** [comment] 2016-07-19 17:52
@rhamilto I don't think reducing the width of the interior lines is painting us into a corner. Here are some options:
![options](https://cloud.githubusercontent.com/assets/6415742/16960579/11bd13ee-4db8-11e6-9f3a-45dd54168874.png)

**Comment by rhamilto** [comment] 2016-07-19 18:43
@ajacobs21e, Thanks.  

I was specifically referring to how to deal with the environments headings that are to come at some point in the future when the horizontal dividers abut the vertical edges.

For the purposes of illustrating what I mean...

![with-environments](https://cloud.githubusercontent.com/assets/895728/16962339/2084bdbc-4dbf-11e6-995c-fd56eab849f5.png)

**Comment by ajacobs21e** [comment] 2016-07-19 18:44
the arrows work too. is html entity rarr the skinnier arrow? If so I prefer that one. 

Of the ones I posted I think I like no interior lines best. (I accidentally deleted the line between the build info block and the pipeline, that one should still be there.)

**Comment by ajacobs21e** [comment] 2016-07-19 18:47
@rhamilto I think that actually works with the "open" right and left sides. We will definitely have to review the visual design for environments when the time comes.

**Comment by rhamilto** [comment] 2016-07-19 18:51
> Of the ones I posted I think I like no interior lines best. (I accidentally deleted the line between the build info block and the pipeline, that one should still be there.)

No lines makes sense when there is only one stage per row, but it's not as clear when two or more stages are present per row.  Maybe that's the solution?  Drop the lines when only one stage per row?

**Comment by ajacobs21e** [comment] 2016-07-19 19:07
![help](https://cloud.githubusercontent.com/assets/6415742/16962988/28ccb1d4-4dc2-11e6-8c94-ea91bf2f291e.png)
The pipeline still flows left to right with the linear colored bars and arrows. Taking out the interior dividers makes the pipeline look continuous instead of broken up.

**Comment by rhamilto** [comment] 2016-07-19 19:25
> Taking out the interior dividers makes the pipeline look continuous instead of broken up.

My eye wants to scan vertically without the dividers.  @jwforres, @spadgett, @sg00dwin ?

**Comment by ajacobs21e** [comment] 2016-07-19 19:34
UXD-visual's recommendation is that the lines were breaking up the actual understanding of the info so do take out interior dividers or use other dividers that maintain the horizontal flow, such as:
![q](https://cloud.githubusercontent.com/assets/6415742/16963777/1cec295e-4dc6-11e6-913e-c64874d8aa62.png)

or revising the design
![screen shot 2016-07-19 at 3 30 18 pm](https://cloud.githubusercontent.com/assets/6415742/16963784/24d1a9be-4dc6-11e6-8ed8-933b600d696e.png)

Either of those would affect overview and pipeline details pages so we'd have to consider that if we want to investigate either option.

**Comment by rhamilto** [comment] 2016-07-20 13:48
Ok.  Given the current scope, I think this should be the final iteration of the visual enhancements.

![320px](https://cloud.githubusercontent.com/assets/895728/16988621/fca923b0-4e5e-11e6-852a-d1b8e15074db.png)
![400px](https://cloud.githubusercontent.com/assets/895728/16988618/fca8377a-4e5e-11e6-802b-8656d23fa5b1.png)
![600px](https://cloud.githubusercontent.com/assets/895728/16988619/fca85098-4e5e-11e6-9635-7a66d242e5b3.png)
![800px](https://cloud.githubusercontent.com/assets/895728/16988623/fca986d4-4e5e-11e6-8e97-d6cb93f95fdd.png)
![1000px](https://cloud.githubusercontent.com/assets/895728/16988622/fca9214e-4e5e-11e6-9a6f-da751c956765.png)
![1200px](https://cloud.githubusercontent.com/assets/895728/16988620/fca8fc3c-4e5e-11e6-9874-cb4fb21b4170.png)
![1600px](https://cloud.githubusercontent.com/assets/895728/16988624/fcb11278-4e5e-11e6-8960-b63c1d8377f8.png)

**Comment by spadgett** [comment] 2016-08-03 14:27
Fixed by #186

**Closed by spadgett** 2016-08-03 14:27 UTC
Labels: kind/bug, priority/P3
