### ISSUE TITLE
A  container-terminal issue

### ISSUE THREAD

**Issue by hcpaas** [openshift/origin-web-console#1713] opened 2017-06-15 03:43 UTC
Hello! 
         use "vi" or "cat" cmd in container-terminal , when the cursor moves the file will show the confusion

        
![issue](https://user-images.githubusercontent.com/19142861/27164341-379ec164-51bf-11e7-811e-1fdb50c3994a.png)

**Comment by funnyblack** [comment] 2017-06-15 04:38
I've got the same problem. 
And sometimes when i use vi command to open a html file ,it shows nothing. But when i use cat command, then i can see the content.

**Comment by jwforres** [comment] 2017-06-16 16:41
@hcpaas sorry its not clear what you are saying the problem is. An animated GIF of you recreating the issue might be more useful in this case.

@funnyblack this is not something we've heard of happening before and the container terminal hasn't changed in quite some time.  What browser do you see this happen in? Is the image you are using for this container based on one of the redhat/openshift SCL builder images or something else?

**Comment by jwforres** [comment] 2017-06-29 12:43
@hcpaas @funnyblack please see my previous comment, if we don't get any additional information we'll be closing the issue

**Comment by spadgett** [comment] 2017-06-30 13:04
Does this happen with `oc rsh` as well? Does this happen with any container or one specific container? What is the value of your `$TERM` env variable?

**Comment by spadgett** [comment] 2017-08-18 14:43
We've completely replaced the terminal implementation with xterm.js in 3.7. Closing due to inactivity and because the underlying implementation has completely changed.

**Closed by spadgett** 2017-08-18 14:43 UTC
