### ISSUE TITLE
Autoscaler's "CPU Limit Target" in UI does not match what the CLI returns

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin-web-console#1590] opened 2017-05-25 13:51 UTC
To reproduce this issue:
1. From the Deployment UI > Actions > Add autoscaler, then set "CPU Limit Target" to 72. Click on save and confirm that the UI shows 72%:
<img width="237" alt="screen shot 2017-05-25 at 6 15 34 pm" src="https://cloud.githubusercontent.com/assets/638577/26452771/6857b558-4176-11e7-8089-82658e47cc5b.png">

2. Using the CLI, run `oc get hpa` and notice it doesn't match the UI:
```
NAME               REFERENCE                           TARGET    CURRENT   MINPODS   MAXPODS   AGE
php-laravel-todo   DeploymentConfig/php-laravel-todo   600%      2%        1         3         14m
```

`oc describe hpa/php-laravel-todo` also shows the issue:
```
Name:				php-laravel-todo
Namespace:			examples
Labels:				app=php-laravel-todo
Annotations:			<none>
CreationTimestamp:		Thu, 25 May 2017 18:00:53 +0430
Reference:			DeploymentConfig/php-laravel-todo
Target CPU utilization:		600% <<<<<<<< not 72%
Current CPU utilization:	4%
Min replicas:			1
Max replicas:			3
No events.
```

The min and max replica counts match.

```
$ oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server XXX
openshift v1.5.0
kubernetes v1.5.2+43a9be4
```

Tested with Chrome and FireFox.

**Comment by spadgett** [comment] 2017-05-25 14:15
@alikhajeh1 When overcommit is configured for the cluster, the web console shows the target as a percentage of CPU **limit**, whereas the CLI is showing it as a percentage of CPU **request**. See also

https://github.com/openshift/origin/issues/13907#issuecomment-297714714

Unfortunately this is confusing if you use both the CLI and web console. @jwforres I think we should look at the user experience here.

**Comment by jwforres** [comment] 2017-05-25 15:32
Closing this one since it is a duplicate of https://github.com/openshift/origin/issues/13907

**Closed by jwforres** 2017-05-25 15:32 UTC
