### ISSUE TITLE
Icon not showing up for Grafana template

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2767] opened 2018-02-04 20:53 UTC
https://github.com/openshift/origin/blob/master/examples/grafana/grafana.yaml

It uses `iconClass: icon-cogs`. The icon isn't showing up the in web console.

/assign
/kind bug
/priority p2

**Comment by spadgett** [comment] 2018-02-04 22:12
Best I can tell, `icon-cogs` doesn't exist, although it's used several places in origin templates.

```
test/testdata/template_multiple_resource_gvs.yaml
10:    iconClass: icon-cogs

examples/heapster/heapster-standalone.yaml
9:    iconClass: icon-cogs

examples/grafana/grafana.yaml
10:    iconClass: icon-cogs

examples/prometheus/prometheus-standalone.yaml
9:    iconClass: icon-cogs

examples/prometheus/prometheus.yaml
9:    iconClass: icon-cogs
```

Lowering priority since it doesn't seem to be a bug, although we should update the templates.

**Comment by spadgett** [comment] 2018-02-05 13:25
/assign @rhamilto 

Can you confirm that `icon-cogs` isn't valid?

**Comment by rhamilto** [comment] 2018-02-05 14:13
[icon-cogs was removed](https://github.com/openshift/origin-web-console/commit/79909e7599a80ffc80bf62e0cd57507f8c54adf0#diff-fd9f9788aef44a46d47e5c9d8475116f) as it was part of a deprecated set of icons that had been carried forward from v2 that we didn't need anymore, **and** it is  a duplicate of [fa-cogs](https://fontawesome.com/v4.7.0/icon/cogs/).  My recommendation is to use "fa fa-cogs" instead of "icon-cogs".

**Closed by rhamilto** 2018-02-05 14:13 UTC
Labels: kind/bug, priority/P3
