### ISSUE TITLE
Got error and success at the same time when deleting a pod

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#1878] opened 2017-07-25 17:12 UTC
Went into the pods list and deleted one using the web ui.. saw this 

![screenshot from 2017-07-25 10-11-54](https://user-images.githubusercontent.com/7328370/28584488-cb644410-7121-11e7-9bfa-259dafada3fe.png)

/cc @jwforres

**Comment by spadgett** [comment] 2017-07-25 17:37
It looks like the DELETE request had a non-zero error code, but the pod got a `deletionTimestamp` anyway (Schrödinger's pod).

@stevekuznetsov Is this reproducible? Would be good to see the full HTTP response in the browser dev tools.

**Comment by stevekuznetsov** [comment] 2017-07-25 17:57
I see this:

```
Error: this.resourceListURL is not a function
n@https://api.ci.openshift.org/console/scripts/vendor.js:59738:45
link/e.openDeleteModal/</<@https://api.ci.openshift.org/console/scripts/vendor.js:59770:34
h@https://api.ci.openshift.org/console/scripts/vendor.js:6053:18
i/<@https://api.ci.openshift.org/console/scripts/vendor.js:6061:1
$eval@https://api.ci.openshift.org/console/scripts/vendor.js:6362:8
$digest@https://api.ci.openshift.org/console/scripts/vendor.js:6318:11
$apply@https://api.ci.openshift.org/console/scripts/vendor.js:6388:1
i@https://api.ci.openshift.org/console/scripts/vendor.js:5367:100
u@https://api.ci.openshift.org/console/scripts/vendor.js:5432:36
Kb/</x.onload@https://api.ci.openshift.org/console/scripts/vendor.js:5443:63
```

**Comment by spadgett** [comment] 2017-07-25 18:06
This was previously fixed by https://github.com/openshift/origin-web-common/pull/29

**Comment by spadgett** [comment] 2017-07-25 18:07
And origin-web-console #1404

**Closed by spadgett** 2017-07-25 18:06 UTC
Labels: kind/bug, priority/P2
