### ISSUE TITLE
In monitoring tab, no hints on valid inputs

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#313] opened 2016-08-08 11:56 UTC
I'm trying to filter by Severity and don't know what severities exist. Trying to filter by Reason I only know those for which I can see a Reason in the actual list.
It would be great if for those tabular values, when I start typing there is a hint on the existing values like in the Deployments filter.

**Comment by spadgett** [comment] 2016-08-09 12:46
Is this after clicking "View Details" for events?

The problem is that the content on the page filters as you type. It's strange to show suggestions, but also update the page dynamically. We tried this in the catalog page, and it didn't work well. I'd rather have a checkbox to show only warnings.

**Comment by jorgemoralespou** [comment] 2016-08-09 17:33
@spadgett while I understand I don't think that's homogeneous behaviour. If you look into other filters, don't filter as you type and allow you to filter with more knowledge on what you're filtering.

**Comment by spadgett** [comment] 2016-08-09 17:37
It's a text search across different fields in the event object, including event messages. I'm not sure what we would show in the list.

**Comment by jorgemoralespou** [comment] 2016-08-09 17:41
@spadgett then why is there a dropdown to select what to filter? I've opened another issue https://github.com/openshift/origin-web-console/issues/333 as a result of not understanding this. Now I guess this is as expected and the dropdown is just for the ordering, which is at all not clear.

**Comment by spadgett** [comment] 2016-08-09 17:55
The dropdown is for ordering, yes.

**Comment by spadgett** [comment] 2016-08-09 18:02
@jorgemoralespou I'm going to close this, and we'll look at improving the sort control under #333. I agree it's confusing.

**Closed** 2016-08-09 18:03 UTC
Labels: kind/enhancement, priority/P3
