### ISSUE TITLE
Grunt add-redirect-uri task is out of date

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2082] opened 2017-09-15 03:29 UTC
```bash
Running "add-redirect-uri" task
oc --server https://localhost:8443 patch oauthclient/openshift-web-console -p {"redirectURIs":["https://localhost:9000/"]}
>> Error: Error from server (Forbidden): User "developer" cannot get oauthclients at the cluster scope: User "developer" cannot get oauthclients at the cluster scope (get oauthclients openshift-web-console)
```

**Comment by spadgett** [comment] 2017-09-15 12:31
It's not out of date, just not always needed. You also need to be `system:admin` for it to work. We could consider taking it out if we're always using cluster up.

Duplicate of #688

**Closed by spadgett** 2017-09-15 12:31 UTC

**Comment by benjaminapetersen** [comment] 2017-09-15 14:08
Ah, I just saw it error out during the test flow.  Prob will just drop that task then.
