### ISSUE TITLE
Error updating route certificates

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#1930] opened 2017-08-13 15:42 UTC
I'm getting an error updating route certificates with the web console in 3.6

```
Reason: Route "dashboard" is invalid: spec.tls.certificate: Invalid value: "redacted": field is immutable
```

Updating the cert in the CLI works.

**Comment by spadgett** [comment] 2017-08-14 12:14
I can reproduce. @knobunc Is `spec.tls.certificate` now immutable?

**Comment by andrewklau** [comment] 2017-08-14 12:35
Editing in the cli works though

**Comment by spadgett** [comment] 2017-08-14 12:36
@andrewklau Did you use `oc edit` to change the cert?

I tried Edit YAML in the web console, which also fails. The CLI uses HTTP PATCH, however, while the web console uses PUT.

**Comment by andrewklau** [comment] 2017-08-14 12:39
yeah `oc edit`, I didn't try editing the yaml in web console

**Comment by spadgett** [comment] 2017-08-14 20:22
@andrewklau I opened an origin issue for this because I don't think it's specific to the web console.

https://github.com/openshift/origin/issues/15772

Closing the issue here so that it's not tracked in two places.

**Closed by spadgett** 2017-08-14 20:22 UTC
Labels: kind/bug, priority/P1
