### ISSUE TITLE
select project dropdown errors

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#1965] opened 2017-08-24 20:02 UTC
<img width="662" alt="screen shot 2017-08-24 at 4 00 23 pm" src="https://user-images.githubusercontent.com/8974593/29686058-8ba363c0-88e5-11e7-8343-eca458960e4d.png">

**Comment by spadgett** [comment] 2017-08-24 20:52
Lowering the priority because this is not reproducible

**Comment by benjaminapetersen** [comment] 2017-08-25 19:31
@ncameronbritt any details about what you were doing? Was this while choosing a project from the top nav, or choosing a project on the membership page (or some other project picker)?

All of the `504` server timeout errors are interesting as well.  Possibly a fresh `oc cluster up` or `grunt serve` that wasn't quite ready to roll?

**Comment by ncameronbritt** [comment] 2017-08-25 19:41
I did oc cluster up with a newly-built oc, and freshly pulled origin. I ran the commands to allow access to the Template Broker. That's it. And it happened two times after doing oc cluster up. 

Docker had not been restarted in a while, don't know if that could be a culprit.

**Comment by benjaminapetersen** [comment] 2017-08-25 19:51
I suspect partial, though it means one of our UI components doesn't fail gracefully if data it expects doesn't appear. 

Best I can guess, the origin via `vendor.js` is in `origin-web-catalog` here:

```
./components/select-project/select-project.controller.ts:  public onSelectProjectChange () {
./components/select-project/select-project.controller.ts:        this.onSelectProjectChange ();
./components/select-project/select-project.controller.ts:        this.onSelectProjectChange ();
./components/select-project/selectProject.html:        ng-change="$ctrl.onSelectProjectChange()"
```
It looks like @dtaylor113 knows this file best, quick ping to see if he might have a good idea.

**Comment by benjaminapetersen** [comment] 2017-08-25 19:54
Pretty sure its complaining about this line: https://github.com/openshift/origin-web-catalog/blame/master/src/components/select-project/select-project.controller.ts#L82

For some reason `this.ctrl.forms.selectProjectForm` must not have rendered/registered.

**Comment by spadgett** [comment] 2017-08-25 20:21
I thought we disabled the `canIAddToProject` check. Am I mistaken?

**Comment by benjaminapetersen** [comment] 2017-08-25 20:49
Not sure, I followed the error stack trace trail via `grep` to get this far.

**Comment by spadgett** [comment] 2017-09-13 15:42
@ncameronbritt Are you still seeing this?

**Comment by ncameronbritt** [comment] 2017-09-13 15:45
Nope. It was just that one day.

**Comment by spadgett** [comment] 2017-09-13 15:48
OK, I haven't seen this either. The dropdown has also had some fixes since this was opened. Closing for now. We can reopen if we see it again.

Thanks @ncameronbritt

**Closed by spadgett** 2017-09-13 15:48 UTC
Labels: kind/bug, priority/P2
