### ISSUE TITLE
Deploying an ImageStream Tag displays the wrong ImageStream name

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin-web-console#973] opened 2016-12-02 08:19 UTC
When deploying an image through **Add to Project** &rarr; **Deploy Image** &rarr; **Image Stream Tag**, if the `ImageStream` name is different from the application name, wrong `ImageStream` name is displayed since it assumes the `ImageStream` and application names are the same. In the following example the `ImageStream` being deployed is `myapp-dev:preprod` and the application name is `myapp-preprod`.  In the middle of the screen, the image to be deployed is displayed as `myapp-preprod:preprod` which does not exist.

<img width="1195" alt="deploy-is" src="https://cloud.githubusercontent.com/assets/1174934/20827059/97273362-b86f-11e6-982a-02837fe3afd7.png">

**Comment by siamaksade** [comment] 2016-12-02 08:19
oc v3.3.1.3
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://api.ded-int-aws.openshift.com:443
openshift v3.3.1.3
kubernetes v1.3.0+52492b4

**Comment by spadgett** [comment] 2016-12-02 12:58
Duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1375480

Fixed by #534 and #535

Although this should be fixed in the reported version. @siamaksade You are using OCP 3.3.1 and not origin, correct?

cc @jwforres

**Comment by siamaksade** [comment] 2016-12-02 14:40
Correct. I just verified with Origin 1.4.0-RC1 and got the same behaviour:
```
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.2.2.15:8443
openshift v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
```

**Comment by spadgett** [comment] 2016-12-02 15:37
Ah, the bug is what it is displaying, but it uses the right image stream in the deployment config. We missed that in the fix for #534.

**Comment by spadgett** [comment] 2016-12-02 15:39
Actually I don't see the problem. It doesn't say an image stream name. That's the deployment config name.

**Comment by siamaksade** [comment] 2016-12-02 16:00
Deployment config doesn't have a tag and therefore cannot be referred to with NAME:TAG format. In that case, we should drop the :TAG part.

**Closed** 2016-12-02 18:46 UTC
Labels: kind/bug, priority/P2
