### ISSUE TITLE
Sort by popup tooltip on events covers dropdown menu and isn't needed

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#438] opened 2016-08-22 14:18 UTC
Suggest we remove the popover tooltip since "sort by" precedes the select field. If not removed, it's behavior should be changed to be positioned above so it doesn't overlay the dropdown menu.
@rhamilto @spadgett any objections?

<img width="603" alt="screen shot 2016-08-22 at 10 16 38 am" src="https://cloud.githubusercontent.com/assets/1874151/17857899/9220699c-6851-11e6-9be4-af1071005869.png">

**Comment by spadgett** [comment] 2016-08-22 14:19
Duplicate of https://github.com/patternfly/angular-patternfly/issues/212

We need to pick up a new version of angular-patternfly to fix.

**Comment by spadgett** [comment] 2016-08-22 14:20
@jwforres I assume we don't want to bump the dependency so close to 1.3

**Comment by jwforres** [comment] 2016-08-22 14:32
would rather not

**Comment by jwforres** [comment] 2016-08-22 20:03
assigning robb since this will be a patternfly related update

**Comment by rhamilto** [comment] 2016-10-17 17:51
Fixed in https://github.com/patternfly/angular-patternfly/releases/tag/v3.8.0

**Closed** 2016-10-31 13:21 UTC
Labels: area/usability, priority/P3
