### ISSUE TITLE
Impossible to add environment variable starting with "app" like application

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#344] opened 2016-08-11 08:24 UTC
I'm deploying an image from an imagestream and trying to create an environment variable called "application". When I start typing and reach "app" the field goes gray and not editable.

I'm using 1.3.0-alpha.3

![image](https://cloud.githubusercontent.com/assets/78350/17582806/ccb802a6-5fad-11e6-9ad4-9b7f7c3104c9.png)

**Comment by benjaminapetersen** [comment] 2016-08-11 14:29
Ah, yeah, for labels we made "app" and "template" readonly :frown:

This is somewhat of a duplicate of this bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1362047, which we will address by eliminating the readonly state on these two "special" labels

**Closed** 2016-08-15 20:33 UTC
Labels: kind/bug, priority/P2
