### ISSUE TITLE
Encountered invalid_request in OAuth process

### ISSUE THREAD

**Issue by llcan1120** [openshift/origin-web-console#114] opened 2016-06-27 17:11 UTC
Hi,

I'm new to origin-web-console. I just setup testing environment in cloud with --hostname=0.0.0.0 and --baseUrl=<real ip:port>. However when i visit https://ip:9000/ i got following error 

```json
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"{\"then\":\"/\",\"nonce\":\"1467047314345-3673651079364708862158794790216584555681010689653270092627925064274853237928925\"}"}
```

the request URL is 

`https://ip:8443/oauth/authorize?client_id=openshift-web-console&response_type=token&state=%7B%22then%22%3A%22%2F%22%2C%22nonce%22%3A%221467047314345-3673651079364708862158794790216584555681010689653270092627925064274853237928925%22%7D&redirect_uri=https%3A%2F%2F52.196.72.38%3A9000%2Foauth`

thanks!

**Comment by liggitt** [comment] 2016-06-27 18:07
the IP you are using to access the web console is likely not in the allowed list for the `openshift-web-console` OAuth client. Do `oc edit oauthclient openshift-web-console` and add a redirect URL to the console's IP (e.g. `https://52.196.72.38:9000`)

**Comment by jwforres** [comment] 2016-07-11 12:03
@llcan1120 did @liggitt's answer resolve your problem or are you still hitting that error

**Comment by jwforres** [comment] 2016-08-05 20:34
Closing due to age, if you are still having a problem re-open with additional info

**Closed by jwforres** 2016-08-05 20:34 UTC
Labels: kind/question

**Comment by cevn** [comment] 2018-05-23 01:44
I'm having this issue now despite having all sorts of redirect URI's in `oc edit oauthclient openshift-web-console`.

**Comment by wissamir** [comment] 2018-06-10 08:03
I'm having too the same issue above
in my configuration I have 3 master nodes behind a load balancer
oc get nodes -l node-role.kubernetes.io/master=true
NAME      STATUS    ROLES     AGE       VERSION
oso1      Ready     master    4d        v1.9.1+a0ce1bc657
oso2      Ready     master    4d        v1.9.1+a0ce1bc657
oso3      Ready     master    4d        v1.9.1+a0ce1bc657

and editing oauthclient openshift-web-console, I already see a redirect IP to the load balancer (lb.e4dot)

apiVersion: oauth.openshift.io/v1
grantMethod: auto
kind: OAuthClient
metadata:
  creationTimestamp: 2018-06-05T13:40:10Z
  name: openshift-web-console
  resourceVersion: "2"
  selfLink: /apis/oauth.openshift.io/v1/oauthclients/openshift-web-console
  uid: f7455390-68c5-11e8-b866-0050568f2bf9
redirectURIs:
- https://lb.e4dot:8443/console/


any clue of what would be the cause of the problem?

**Comment by amrit28** [comment] 2018-06-25 18:59
I am also facing the same issue.
1. Run command "grunt build" and "grunt serve" in origin-web-console to launch the openshift webconsole
2. It executed successfully and launched on https://xx.xx.xx.xx:9000
Now, when i am trying to access this url then it opens the url and suddenlly it is redirecting to
https://xx.xx.xx.xx:8443:8443/oauth/authorize?client_id=openshift-web-console&response_type=code&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTUyOTU5ODQ4NzA1Mi0zOTM2MTcxNzYzODU3Mjg0MDA3MTY4ODM4MzE0OTQxMzQ5Nzc0OTgxOTM3MzA1NzI4Mjg1MzYxODU0MDI4MDA0NDcyNTMxNzMxNDQwNjM0In0&redirect_uri=https%3A%2F%2F172.30.65.137%3A9000%2Fdev-console%2Foauth"

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise

**Comment by Activeghost** [comment] 2019-02-16 08:31
I am also seeing this issue, where the URI redirect in OAUTH config was incorrect, so I patched it and removed the internal IP it was attempting to redirect to ...which is the IP you see here (post removal and delete / restart of the web console pod): 

[https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443/oauth/authorize?client_id=openshift-web-console&response_type=code&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTU1MDMwMzczNTA1OS05MzgyMzIyMjMwNjIyODg2MjE0OTI2Njg0OTM4NzgyNDkwMzAyNzY3MTQzNzc2MjU0NjU1MDY5MzM4Mjc1MTE2NjcxNjU3MzMyNDExIn0&redirect_uri=https%3A%2F%2Fip-10-0-0-14.us-west-2.compute.internal%3A8443%2Fconsole%2Foauth](https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443/oauth/authorize?client_id=openshift-web-console&response_type=code&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTU1MDMwMzczNTA1OS05MzgyMzIyMjMwNjIyODg2MjE0OTI2Njg0OTM4NzgyNDkwMzAyNzY3MTQzNzc2MjU0NjU1MDY5MzM4Mjc1MTE2NjcxNjU3MzMyNDExIn0&redirect_uri=https%3A%2F%2Fip-10-0-0-14.us-west-2.compute.internal%3A8443%2Fconsole%2Foauth)

I'm not sure where it's picking this up from as I've also changed the masterPublicUrls in the master config to use that address (somewhere during install it set these all to the private uri's). After which I ran  the playbook to restart the master.

Looking at the oauth configuration I still see an internal redirect URI (although not sure if that is supposed to look like that or not).

```
 oc describe oauthclient openshift-console
Name:          openshift-console
Namespace:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"oauth.openshift.io/v1","grantMethod":"auto","kind":"OAuthClient","metadata":{"annotations":{},"name":"openshift-console","namespace":""}...
API Version:   oauth.openshift.io/v1
Grant Method:  auto
Kind:          OAuthClient
Metadata:
  Creation Timestamp:  2019-02-16T06:16:40Z
  Resource Version:    2694
  Self Link:           /apis/oauth.openshift.io/v1/oauthclients/openshift-console
  UID:                 6c7224d8-31b2-11e9-87af-062f3d8b2eaa
Redirect UR Is:
  https://console.router.default.svc.cluster.local/
Secret:  xHtbBGn7TLEXRk1DuSBB0uJaFtpTF4Pj
Events:  <none>
```


Editing the oathclient/openshift-web-console I see this:

```
piVersion: oauth.openshift.io/v1
grantMethod: auto
kind: OAuthClient
metadata:
  creationTimestamp: 2019-02-16T06:08:58Z
  name: openshift-web-console
  resourceVersion: "17889"
  selfLink: /apis/oauth.openshift.io/v1/oauthclients/openshift-web-console
  uid: 58ea9d15-31b1-11e9-87af-062f3d8b2eaa
redirectURIs:
- https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443/
- https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443/console/
```

...which is what I expected to see after removing the internal ip (what it is still trying to redirect to) and added the others. 

```
oc get --raw '/.well-known/oauth-authorization-server'
{
  "issuer": "https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443",
  "authorization_endpoint": "https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443/oauth/authorize",
  "token_endpoint": "https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443/oauth/token",
  "scopes_supported": [
    "user:check-access",
    "user:full",
    "user:info",
    "user:list-projects",
    "user:list-scoped-projects"
  ],
  "response_types_supported": [
    "code",
    "token"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
```

UPDATE: 

Checking the last applied config it still has the older configuration applied. Not sure how that is when I restarted the master api.

```
oc get -o yaml configmap console-config -n openshift-console
apiVersion: v1
data:
  console-config.yaml: |
    apiVersion: console.openshift.io/v1beta1
    auth:
      clientID: openshift-console
      clientSecretFile: /var/oauth-config/clientSecret
      logoutRedirect: ''
      oauthEndpointCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    clusterInfo:
      consoleBaseAddress: https://console.router.default.svc.cluster.local
      consoleBasePath: ''
      developerConsolePublicURL: https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443/console/
      masterPublicURL: https://ec2-34-220-25-45.us-west-2.compute.amazonaws.com:8443
    customization:
      branding: okd
      documentationBaseURL: https://docs.okd.io/4.0/
    kind: ConsoleConfig
    servingInfo:
      bindAddress: https://0.0.0.0:8443
      certFile: /var/serving-cert/tls.crt
      keyFile: /var/serving-cert/tls.key
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"console-config.yaml":"apiVersion: console.openshift.io/v1beta1\nauth:\n  clientID: openshift-console\n  clientSecretFile: /var/oauth-config/clientSecret\n  logoutRedirect: ''\n  oauthEndpointCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\nclusterInfo:\n  consoleBaseAddress: https://console.router.default.svc.cluster.local\n  consoleBasePath: ''\n  developerConsolePublicURL: https://ip-10-0-0-14.us-west-2.compute.internal:8443/console/\n  masterPublicURL: https://ip-10-0-0-14.us-west-2.compute.internal:8443\ncustomization:\n  branding: okd\n  documentationBaseURL: https://docs.okd.io/4.0/\nkind: ConsoleConfig\nservingInfo:\n  bindAddress: https://0.0.0.0:8443\n  certFile: /var/serving-cert/tls.crt\n  keyFile: /var/serving-cert/tls.key\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"openshift-console"},"name":"console-config","namespace":"openshift-console"}}
  creationTimestamp: 2019-02-16T06:16:40Z
  labels:
    app: openshift-console
  name: console-config
  namespace: openshift-console
  resourceVersion: "14082"
  selfLink: /api/v1/namespaces/openshift-console/configmaps/console-config
  uid: 6c5b429b-31b2-11e9-87af-062f3d8b2eaa
```

... forced an update by applying this config to the pod and still get the problem. Also edited the OAUTH configuration for the openshift-console to change the redirect to the public URI and still see the redirect to the local. As soon as I add the URI for https://ip-10-0-0-14.us-west-2.compute.internal:8443/ back it will not error and does indeed redirect there (obvious from the uri, yes). Have no idea where this IP is coming from.

... also updated openshift-web-console oauth and config maps similarly to the openshift-console to no avail.
