### ISSUE TITLE
oc scale not taking effect inmediatelly and not shown in console

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#45] opened 2016-05-27 10:42 UTC
I have done this in command line:
`````
[vagrant@origin ~]$ oc new-app kubernetes/guestbook
--> Found Docker image 4305190 (19 months old) from Docker Hub for "kubernetes/guestbook"

    * An image stream will be created as "guestbook:latest" that will track this image
    * This image will be deployed in deployment config "guestbook"
    * Port 3000/tcp will be load balanced by service "guestbook"
      * Other containers can access this service through the hostname "guestbook"
    * WARNING: Image "kubernetes/guestbook" runs as the 'root' user which may not be permitted by your cluster administrator

--> Creating resources with label app=guestbook ...
    imagestream "guestbook" created
    deploymentconfig "guestbook" created
    service "guestbook" created
--> Success
    Run 'oc status' to view your app.
````
In the UI I see this:
![image](https://cloud.githubusercontent.com/assets/78350/15604759/5a21f1fc-2402-11e6-8a41-a470f72370e0.png)

Inmediately I do a scaling:
`````
[vagrant@origin ~]$ oc scale kubernetes/guestbook --replicas=10
the server doesn't have a resource type "kubernetes"
[vagrant@origin ~]$ oc scale dc/guestbook --replicas=10
deploymentconfig "guestbook" scaled
[vagrant@origin ~]$ oc get dc
NAME        REVISION   REPLICAS   TRIGGERED BY
guestbook   1          10         config,image(guestbook:latest)
[vagrant@origin ~]$ oc get pods --no-headers | wc -l
1
````
I can see that now there¡s 10 pods requested, but still 1 pod.

**UI Does not reflect this. THIS IS THE ERROR/ISSUE**

In the UI I see this:
![image](https://cloud.githubusercontent.com/assets/78350/15604759/5a21f1fc-2402-11e6-8a41-a470f72370e0.png)

Then after 2 minutes (or so, state consolidation):
I see the console updated:
![image](https://cloud.githubusercontent.com/assets/78350/15604811/897a4670-2402-11e6-99a2-cccbfa4d227b.png)

````
[vagrant@origin ~]$ oc get pods --no-headers | wc -l
10
````

If I scale now to 20 from CLI:
`````
[vagrant@origin ~]$ oc scale dc/guestbook --replicas=20
deploymentconfig "guestbook" scaled
[vagrant@origin ~]$ oc get dc
NAME        REVISION   REPLICAS   TRIGGERED BY
guestbook   1          20         config,image(guestbook:latest)
[vagrant@origin ~]$ oc get pods --no-headers | wc -l
20
`````

I see immediate change in console.


![image](https://cloud.githubusercontent.com/assets/78350/15604674/ea5916ac-2401-11e6-9d1a-2e2801297750.png)

**Comment by spadgett** [comment] 2016-05-27 11:24
@jorgemoralespou I'm not able to reproduce even running your exact commands. Does it happen every time for you?

Your donut turned yellow, which means your pods had warnings. If reproducible, can you check what the warnings are on the browse pods page?

**Comment by jorgemoralespou** [comment] 2016-05-27 12:29
@spadgett Seems like @kargakis is triaged this in the original bug in origin as not console related. You can talk to him.

**Comment by jorgemoralespou** [comment] 2016-05-27 12:32
But yes, it's reproducible, there 's no issue when creating those containers. They show yellow but no strange events and they start ok.

**Comment by spadgett** [comment] 2016-05-27 12:33
> Seems like @kargakis is triaged this in the original bug in origin as not console related. You can talk to him.

Thanks @jorgemoralespou, closing for now. We can reopen if we need to make a console change.

**Closed by spadgett** 2016-05-27 12:33 UTC
