### ISSUE TITLE
"Create" where "Close" should be on results pane

### ISSUE THREAD

**Issue by djzager** [openshift/origin-web-console#2063] opened 2017-09-13 13:31 UTC
![https://imgur.com/Y78KevQ](https://imgur.com/Y78KevQ.png)

I was working through [Provision + Bind workflows](https://imgur.com/a/p2XYb) with Ansible Playbook Bundles in OpenShift 3.7 (built from source ref: 7ddd016072) and found this scenario where I expected to see "Close".

**Comment by spadgett** [comment] 2017-09-13 15:40
cc @jeff-phillips-18

**Comment by spadgett** [comment] 2017-09-13 17:54
@djzager If you still have an environment to test this, can you check if there are any errors in the JavaScript console in your browser's dev tools?

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser

**Comment by spadgett** [comment] 2017-09-15 19:54
I'm unable to reproduce.

**Comment by spadgett** [comment] 2017-10-06 18:22
Closing as this can't be reproduced and we don't have enough info to debug further.

**Closed by spadgett** 2017-10-06 18:22 UTC
Labels: kind/bug, priority/P2
